import re
from playwright.sync_api import Page, expect

def test_orange_hrm(page):
    page.goto("https://www.saucedemo.com/")
    #page.locator("[data-test=\"username\"]").click()
    page.locator("[data-test=\"username\"]").fill("standard_user")
    #page.locator("[data-test=\"password\"]").click()
    page.locator("[data-test=\"password\"]").fill("secret_sauce")
    #page.locator("[data-test=\"login-button\"]").click()
    expect(page.locator("[data-test=\"primary-header\"]")).to_contain_text("Swag Labs")
    # page.locator("[data-test=\"product-sort-container\"]").select_option("lohi")
    # page.locator("[data-test=\"add-to-cart-sauce-labs-onesie\"]").click()
    # page.locator("[data-test=\"add-to-cart-sauce-labs-bolt-t-shirt\"]").click()
    # page.locator("[data-test=\"add-to-cart-sauce-labs-backpack\"]").click()
    # page.locator("[data-test=\"add-to-cart-sauce-labs-fleece-jacket\"]").click()
    # page.locator("[data-test=\"remove-sauce-labs-bolt-t-shirt\"]").click()
    # page.locator("[data-test=\"add-to-cart-sauce-labs-bike-light\"]").click()
    # page.locator("[data-test=\"remove-sauce-labs-onesie\"]").click()
    # page.locator("[data-test=\"shopping-cart-link\"]").click()
    # page.locator("[data-test=\"checkout\"]").click()
    # page.locator("[data-test=\"firstName\"]").click()
    page.locator("[data-test=\"firstName\"]").fill("Isha")
    page.locator("[data-test=\"firstName\"]").press("Tab")
    page.locator("[data-test=\"lastName\"]").fill("S")
    # page.locator("[data-test=\"postalCode\"]").click()
    page.locator("[data-test=\"postalCode\"]").fill("V9A5j1")
    # page.locator("[data-test=\"continue\"]").click()
    # page.locator("[data-test=\"finish\"]").click()
    expect(page.locator("[data-test=\"complete-header\"]")).to_be_visible()
    expect(page.locator("[data-test=\"complete-header\"]")).to_contain_text("Thank you for your order!")
    # page.locator("[data-test=\"back-to-products\"]").click()
